### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by landmanmanc** [75lb/local-web-server#15]
I want to use [Sourcegraph](https://sourcegraph.com) for local-web-server code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/75lb/local-web-server. (It should only take 30 seconds.)

Thank you!

**Comment by 75lb** [comment]
Sourcegraph seems completely broken atm, most searches return a 404 and my projects are failing to build.. but none-the-less, i enabled it as requested..
