### ISSUE TITLE
Server says: level_15 or view access

### ISSUE THREAD

**Issue by pli88** [75lb/local-web-server#16]
When tried to access the test page in my mobile. A popup shows with the message 

```
Authentication Required
The server at http://xxx.xx.x.x:80 requires a user name and password.
The server says level_15 or view_access
```
What to  change in configuration setting to avoid this login?

**Comment by 75lb** [comment]
Odd.. do you get this when serving all files, or just particular files?

**Comment by pli88** [comment]
For eveything. Authentication popup is the first thing shows up.

When tried with port number webpage not available shows. When tried without port number Authentication popup shows up.

Am i missing something here?

**Comment by 75lb** [comment]
i can't reproduce this.. i think you are accessing the wrong web server.. the default port of local-web-server is 8000, but in your example above you are hitting port 80.
