### ISSUE TITLE
How can I add rewrite-rules?

### ISSUE THREAD

**Issue by markusbrunner-design** [75lb/local-web-server#20]
Like in the npm-server "web-server-rewrite" I really need http-rewrite-rules with regular expressions. But:
1. I really like your local-web-server
2. I can't get the web-server-rewrite to work because of problems with the execSync-Dependency

What for is this? It's especially for services which need to be rewritten to another url in local and live-environment, e.g.:

 rewrites
```
 {
    "localhost": {
      "(.*)(/users/)(.*)": "http://myserver1.mw.domain.lan:10080/middleware1/$3",
      "(.*)(/auth/)(.*)": "http://myserver2.mw.domain.lan:10080/auth-service/$3"
    },
   "domain.de": {
    ...
   }
 }
```
This would be very helpful - and if you include the keyword "rewrite" in your descriptions, this would definitely boost your server-implementation!

Regards
Markus

**Comment by 75lb** [comment]
i see.. yes, that looks very useful - i will implement, thanks.

**Comment by 75lb** [comment]
implemented in the [new version](https://github.com/75lb/local-web-server/).. feedback welcome!

```
$ npm install -g local-web-server@^1.0.0-alpha.1
```

**Comment by markusbrunner-design** [comment]
Hey,

at first I wanna thank you for implementing this issue - that's really cool!

Unfortunately the current "configuration" isn't working for me, because I need port-numbers in my rewrite-rule:
=> "http://my.server.lan:10080/myservice/$1"
but they are used via ":" for constants?

Regards
Markus

**Comment by 75lb** [comment]
reproduced, fixing..

**Comment by 75lb** [comment]
i found and fixed an issue regarding rewrite "to" addresses containing port numbers.. can you install `1.0.0-alpha.5` and try again please? 

i successfully tested it with this rewrite rule: (all paths under `/yeah` successfully proxied)
```
$ ws --rewrite '/yeah/* -> http://localhost:9000/$1'
```

**Comment by markusbrunner-design** [comment]
the port-numbers are working now, great!

but it seems like the new rewrite-rule doesn't transfer the query string parameters - which is also necessary for my case and in general

Regards
Markus

**Comment by 75lb** [comment]
thanks again - try the new release, version `v1.0.0-alpha.6` :+1:

**Comment by markusbrunner-design** [comment]
very, very nice! now it works for my use-case!

That's very helpful 75lb!

Regards
Markus

**Comment by 75lb** [comment]
good.. let me know if you have any more issues..
