### ISSUE TITLE
option to define multiple static roots

### ISSUE THREAD

**Issue by 75lb** [75lb/local-web-server#22]
for example, how you would do it express
```
app.use("/assets", serveStatic("./app/assets"));
app.use("/css", serveStatic("./cheese/css"));
etc.
```

**Comment by azerafati** [comment]
Why was this closed?

**Comment by 75lb** [comment]
this ticket is over 6 years old - I think it was closed because you can implement the behaviour in multiple ways with existing features (URL rewriting, custom middleware, possibly even by launching multiple different `ws` instances with separate `--directory` options).

**Comment by azerafati** [comment]
URL rewriting is limited to the same `directory` root (#45) and launching multiple ws instances won't be on the same port. Could you point to an example with custom middleware?

**Comment by 75lb** [comment]
Have a look on the project wiki, particularly the [Creating-middleware](https://github.com/lwsjs/local-web-server/wiki/Creating-middleware) page.. let me know if you have any other questions 👍
