### ISSUE TITLE
'Cannot find module' with mocks

### ISSUE THREAD

**Issue by Kordonme** [75lb/local-web-server#25]
Already scratched my head for far too long...

```
[22:57:00] Error: Cannot find module 'mocks\servers.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

Got this config: 

```
lws({
    'static': {
        'root': './'
    },
    'mocks': [{
        'route': '/',
        'module': '/mocks/servers.js'
    }]
}).listen(2650)
```

Happens on line 151. Basically, it's not able to load the file. However, if I remove the 'module' property, the server starts (of course), and I'm able to navigate to `/mocks/servers.js` and get the content.

**Comment by 75lb** [comment]
this line: 
```
[22:57:00] Error: Cannot find module 'mocks\servers.js'
```

why does it include a backslash (the escape character) rather than a forward slash? odd..

**Comment by 75lb** [comment]
are you on Windows? if so, which version?

**Comment by Kordonme** [comment]
That is odd, yes. Didn't notice that. And yes, Windows 10, `node --version: v5.1.1`

**Comment by Kordonme** [comment]
I tried putting the mock js file (`servers.js`) in same directory. Works fine. Is this a module loading problem on Windows maybe?

**Comment by 75lb** [comment]
checking now, should be a quick fix

**Comment by 75lb** [comment]
finally reproduced after testing on Windows 8 and 10.. while i fix, please test this config for me (static option value removed).. it should behave the same as ws defaults to the current directory.. 

```
lws({
    'mocks': [{
        'route': '/',
        'module': '/mocks/servers.js'
    }]
}).listen(2650)
```

**Comment by Kordonme** [comment]
Thanks!

I tried that already and I'm getting an error:

```
[00:07:46] TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
```

Same line in `local-web-server.js`.

**Comment by 75lb** [comment]
fixed in v1.0.2.. please update and try again.

**Comment by Kordonme** [comment]
You are the best - works like a charm!

**Comment by 75lb** [comment]
good, pleased you like it! If you have any other ideas about how to improve it, let me know :+1:
