### ISSUE TITLE
Feature request: delay response

### ISSUE THREAD

**Issue by Kordonme** [75lb/local-web-server#26]
Is it possible to delay responses in some way? I tried implementing [koa-slow](https://github.com/bahmutov/koa-slow), but no luck. Still instant response. 

It would be cool to be able to implement some sort of delay for mocks. Maybe even with the use of a function, so that I can write my random delay e.g. between 50 and 1500 ms.

I'm not sure of that's out of scope for this project, maybe you have some other ideas?

**Comment by 75lb** [comment]
good point, thanks! 

fixed in v1.1.. you can make your mocked response async by returning a Promise.. see [this example](https://github.com/75lb/local-web-server/blob/master/example/mock-async/mocks/delayed.js) - you can substitute the 2s delay for something random..
