### ISSUE TITLE
JSON-requests not correctly proxied

### ISSUE THREAD

**Issue by markusbrunner-design** [75lb/local-web-server#27]
#PROXY-REWRITE:
local-web-server proxy request +0ms from: /loginservice/de/1234, to: http://myserver/login/de?myId=1234

#local-web-server RESPONSE
curl -v -H "Content-Type:application/json" --data "@testrequest.json" "http://mylocalhost/loginservice/de/1234"
* Hostname was NOT found in DNS cache
* Connected to ... (...) port 8999 (#0)
> POST /loginservice/de/1234 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ...
> Accept: */*
> Content-Type:application/json
> Content-Length: 122
> 
* upload completely sent off: 122 out of 122 bytes
< HTTP/1.1 500 Internal Server Error
* Server Apache-Coyote/1.1 is not blacklisted
< server: Apache-Coyote/1.1
< date: Wed, 16 Dec 2015 09:41:52 GMT
< content-length: 0
< connection: close

#CORRECT RESPONSE VIA DIRECT CALL
* upload completely sent off: 122 out of 122 bytes
< HTTP/1.1 200 OK
< Date: Wed, 16 Dec 2015 09:48:53 GMT
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Content-Type: application/json
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"status":"SUCCESS","resultUri":"..."}

**Comment by 75lb** [comment]
hi marcus.. i don't have enough information to reproduce this, it could be caused by one of several things.. could you send 

* the full URL of the remote endpoint you are hitting ("http://myserver/login/de?myId=1234")
* some example request body data (--data "@testrequest.json" )

if you prefer you can [email me](mailto:75pound@gmail.com) or [use the gitter room](https://gitter.im/75lb/local-web-server)

**Comment by 75lb** [comment]
hi markus, is this still an issue with local-web-server v1.1.1? 

The latest version has an updated `http-proxy` module and also a [significant bug](https://github.com/75lb/local-web-server/issues/30) was fixed..

**Comment by markusbrunner-design** [comment]
Hey Lloyd,I installed the latest version 1.1.1 and retried, but without a remarkable effect. The problem still exists.RegardsMarkusLloyd Brookes <notifications@github.com> hat am 20. Februar 2016 um 17:18 geschrieben:hi markus, is this still an issue with local-web-server v1.1.1?The latest version has an updated http-proxy module and also a significant bug was fixed..—Reply to this email directly or view it on GitHub.

**Comment by 75lb** [comment]
hi Markus.. sorry for the long delay.. i have discovered and fixed an issue today which may also fix your problem.. 

could you run this command (to install `ws` directly from Github) and check if your issue is fixed please? 
```
$ npm i -g 75lb/local-web-server
```

thanks,
Lloyd
