### ISSUE TITLE
[Feature request] Option to run HTTPS without creating key and cert 

### ISSUE THREAD

**Issue by ButuzGOL** [75lb/local-web-server#31]
Now if I want to run HTTPS server I need to have key and cert
Usually I do it for dev so its not big reason what cert to use
so why not create some flag which will run https without having cert and key like ws -s
like in gulp connect https://github.com/avevlad/gulp-connect#optionshttps

**Comment by 75lb** [comment]
[done](https://github.com/75lb/local-web-server#built-in-certificate).. released in v1.2.0, thanks ;)
