### ISSUE TITLE
ext-js memory leak?!

### ISSUE THREAD

**Issue by zerkotin** [75lb/local-web-server#42]
im working with ext-js 6
i compile my app as development (sencha app build development) and use ws
for local js files and as a proxy to my server calls which runs on tomcat.

with every refresh of the page it becomes slower and slower.

worth to mention that ext-js has a cache buster in the URL, maybe its that.
maybe its the multiple calls.

there are 804 requests done from the browser when loading the page.

anyway its really annoying to refresh it every time, if you need further information, ill be glad to give you anything you need.

**Comment by 75lb** [comment]
hi.. interesting! I also work on a large front-end using local-web-server, and proxy to remote APIs.. my front-end makes 800-1000 requests on each load (hideous, i know).. I have never experienced slow-down, but i'm on a MacBook with plenty of RAM so maybe it doesn't affect me so much.. 

Yes, i need more information. 

Is the node.js process (the web server) increasing in memory all the time? Are you certain it's the local-web-server that it leaking memory? Tell me as much as you can..

**Comment by zerkotin** [comment]
im actually not sure whos eating memory, if it is memory at all.
i noticed slowness and i managed to find its the local-web-server

if i restart it, everything goes fast again.

ill check it out...

im running on a windows machine with 16gb of ram.

**Comment by zerkotin** [comment]
ok, false alarm, im sorry, it was my tomcat, running debug port 8000, its killing my requests. its not a memory leak. and theres no problem.
