### ISSUE TITLE
Browser Sync

### ISSUE THREAD

**Issue by johannds** [75lb/local-web-server#51]
Hi,

Awesome tool! Just one question - I am using Browser Sync and it seems to go into an endless refresh loop when hosting through the local-web-server. Is there a way around it? OR rather, is it possible to support rerouting of the ws:// protocol?

Thanks,
Johann

**Comment by 75lb** [comment]
hi Johannds, could you send me a failing test case please? (some code or a gist i can run to see it failing)

I tried Browser Sync briefly in the past but found it doesn't provide any features i don't already have in Chrome DevTools..
